"""add vat fields to line_items

Revision ID: 153e0ac09cbc
Revises: fd784d5b54d1
Create Date: 2026-09-05 17:08:28.178855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153e0ac09cbc'
down_revision: Union[str, Sequence[str], None] = 'fd784d5b54d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('amount_without_vat', sa.Float(), nullable=True))
    op.add_column('line_items', sa.Column('vat_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'vat_rate')
    op.drop_column('line_items', 'amount_without_vat')
    # ### end Alembic commands ###
