"""add content_hash to invoices for duplicate detection

Revision ID: 26c2f3ca067c
Revises: 31240659a926
Create Date: 2026-09-06 11:39:11.731463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c2f3ca067c'
down_revision: Union[str, Sequence[str], None] = '31240659a926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_content_hash'), 'invoices', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_content_hash'), table_name='invoices')
    op.drop_column('invoices', 'content_hash')
    # ### end Alembic commands ###
