"""add currency_confidence to invoices

Revision ID: 31240659a926
Revises: 74d14ee849c1
Create Date: 2026-09-06 11:00:33.954073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31240659a926'
down_revision: Union[str, Sequence[str], None] = '74d14ee849c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default nutný, aby ALTER TABLE nespadl na existujících řádcích -
    # už zpracované faktury dostanou 1.0 (žádné dodatečné varování o měně).
    op.add_column('invoices', sa.Column('currency_confidence', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency_confidence')
    # ### end Alembic commands ###
