"""add fk indexes and processing watchdog fields

Revision ID: 74d14ee849c1
Revises: e9c796a3633f
Create Date: 2026-09-06 10:52:26.081403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d14ee849c1'
down_revision: Union[str, Sequence[str], None] = 'e9c796a3633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # server_default nutný, aby ALTER TABLE nespadl na existujících řádcích -
    # Python-side default=0 v models.py platí jen pro nové INSERTy přes ORM.
    op.add_column('invoices', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_line_items_invoice_id'), 'line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_invoice_id'), table_name='line_items')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_column('invoices', 'retry_count')
    op.drop_column('invoices', 'processing_started_at')
    # ### end Alembic commands ###
