"""add extraction_warning to invoices

Revision ID: e9c796a3633f
Revises: 153e0ac09cbc
Create Date: 2026-09-05 18:10:02.904276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c796a3633f'
down_revision: Union[str, Sequence[str], None] = '153e0ac09cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('extraction_warning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'extraction_warning')
    # ### end Alembic commands ###
