"""add supplier_name and invoice_date to line_items

Revision ID: fd784d5b54d1
Revises: f0c25867437d
Create Date: 2026-09-05 16:47:59.297359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd784d5b54d1'
down_revision: Union[str, Sequence[str], None] = 'f0c25867437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_items', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('invoice_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'invoice_date')
    op.drop_column('line_items', 'supplier_name')
    # ### end Alembic commands ###
